### ISSUE TITLE
issue PaylinkTokenInformationManagement.php  line no 355

### ISSUE THREAD

**Issue by fullstack-mishraravi** [citypay/citypay-paylink-magento#5]
Hi, 
    If in Magento authorize amount and capture amount are not same then order status automatic converted as fraud order. 
    As per this file line no 355  'amount' => (int)(floatval($order->getData('grand_total')) * 100), "
   According to above line if order value is 33.41 than it will 3340.
   Here authorize  amount is 33.41 and capture amount is 33.40 due to order status is return fraud. 
  If we remove "int" then it will be fixed.  otherwise, if you have any other suggestions. @garyfeltham Please suggest to me.

**Comment by garyfeltham** [comment]
Yes that makes sense and may depend on the rounding mode in php. We've added this to review on the next release

**Comment by hectorconceicao** [comment]
This has being fixed on release 1.0.9.
